function lei(n){return Number(n||0).toLocaleString('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2})+' lei';}
function val(id){return parseFloat(document.getElementById(id)?.value)||0;}
function calcLoan(){const amount=val('amount'),annual=val('rate'),years=val('years'),months=years*12,r=annual/100/12; if(!amount||!years){document.getElementById('result').innerHTML='Introdu valorile necesare.';return;} let payment=r?amount*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):amount/months;const total=payment*months;document.getElementById('result').innerHTML=`Rata lunară: <strong>${lei(payment)}</strong><br>Total plătit: <strong>${lei(total)}</strong><br>Dobândă totală: <strong>${lei(total-amount)}</strong>`}
function calcFuel(){const km=val('km'),c=val('consumption'),p=val('price'),liters=km*c/100,cost=liters*p;document.getElementById('result').innerHTML=`Combustibil necesar: <strong>${liters.toFixed(2)} litri</strong><br>Cost estimat: <strong>${lei(cost)}</strong>`}
function calcCar(){const km=val('km'),c=val('consumption'),p=val('price'),m=val('maintenance'),fuel=km*c/100*p,total=fuel+m;document.getElementById('result').innerHTML=`Combustibil: <strong>${lei(fuel)}</strong><br>Alte costuri: <strong>${lei(m)}</strong><br>Cost total: <strong>${lei(total)}</strong>`}
function calcTax(){const a=val('amount'),r=val('rate');document.getElementById('result').innerHTML=`Taxă: <strong>${lei(a*r/100)}</strong><br>Total: <strong>${lei(a*(1+r/100))}</strong>`}
function calcHourly(){const n=val('net'),h=val('hours');document.getElementById('result').innerHTML=h>0?`Câștig aproximativ pe oră: <strong>${lei(n/h)}</strong>`:'Introdu numărul de ore.'}
function calcExpenses(){const i=val('income'),f=val('fixed'),v=val('variable'),t=f+v;document.getElementById('result').innerHTML=`Cheltuieli totale: <strong>${lei(t)}</strong><br>Bani rămași: <strong>${lei(i-t)}</strong>`}
function calcSalary(){const gross=val('gross'),under26=document.getElementById('under26')?.checked,children=parseInt(document.getElementById('children')?.value||0),minimum=4325,nonTaxable=(gross>=4325&&gross<=4600)?200:0,base=gross-nonTaxable,cas=base*.25,cass=base*.10;let bracket=Math.floor((gross-4325)/50);bracket=Math.max(0,Math.min(40,bracket));let basePercent=20-.5*bracket,depBonus=children>=4?25:children*5,deduction=minimum*(basePercent+depBonus)/100,netBeforeTax=base-cas-cass,additional=(under26?.15*minimum:0)+children*100,taxable=Math.max(0,netBeforeTax-deduction-additional),tax=taxable*.10,net=gross-cas-cass-tax;document.getElementById('result').innerHTML=`CAS: <strong>${lei(cas)}</strong><br>CASS: <strong>${lei(cass)}</strong><br>Impozit: <strong>${lei(tax)}</strong><br>Salariu net estimat: <strong>${lei(net)}</strong>`}
